# Generated by Django 2.2.11 on 2020-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('sid', models.CharField(default='', max_length=1000)),
                ('price', models.CharField(default='', max_length=1000)),
                ('desc', models.CharField(default='', max_length=10000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('sid', models.CharField(default='', max_length=1000)),
                ('price', models.CharField(default='', max_length=1000)),
                ('desc', models.CharField(default='', max_length=10000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
