# Generated by Django 2.2.11 on 2020-11-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foo_ds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
