# Generated by Django 2.2.11 on 2020-11-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foo_ds', '0002_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='catname',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
